# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mIkmIiCsOyKYD8k4DaOjI7b3dz4AisIX
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


file_path = '/content/drive/MyDrive/Country Development Indicators.csv'


df = pd.read_csv(file_path)

# GDP
plt.figure(figsize=(10, 6))
sns.boxplot(data=df, y='GDP')
plt.title('Boxplot of GDP')
plt.ylabel('GDP (in billions)')
plt.xlabel('Countries')
plt.grid(True)
plt.show()

# F rate
plt.figure(figsize=(10, 6))
sns.boxplot(data=df, y='Fertility rate, total (births per woman)')
plt.title('Boxplot of Fertility Rate')
plt.ylabel('Fertility Rate (births per woman)')
plt.xlabel('Countries')
plt.grid(True)
plt.show()

# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns

# combined_data = pd.melt(df, id_vars='Country', value_vars=['GDP', 'Fertility rate, total (births per woman)'],
#                         var_name='Indicator', value_name='Value')


# plt.figure(figsize=(10, 6))
# sns.boxplot(x='Indicator', y='Value', data=combined_data)
# plt.title('Boxplot of GDP and Fertility Rate')
# plt.ylabel('Value')
# plt.xlabel('Indicator')
# plt.grid(True)
# plt.show()

# df['GDP (in billions)'] = df['GDP'] / 1e9
df['GDP (in millions)'] = df['GDP'] / 1e6
plt.figure(figsize=(15, 6))


plt.subplot(1, 2, 1)
sns.boxplot(data=df, y='GDP (in millions)')
plt.title('Boxplot of GDP (in millions)')
plt.ylabel('GDP (in millions)')
plt.xlabel('Countries')


plt.subplot(1, 2, 2)
sns.boxplot(data=df, y='Fertility rate, total (births per woman)')
plt.title('Boxplot of Fertility Rate')
plt.ylabel('Fertility Rate (births per woman)')
plt.xlabel('Countries')


plt.tight_layout()


plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


file_path =  '/content/drive/MyDrive/Country Development Indicators.csv'


df = pd.read_csv(file_path)


df['GDP (log scale)'] = np.log1p(df['GDP'])


plt.figure(figsize=(15, 6))

#GDP
plt.subplot(1, 2, 1)
sns.boxplot(data=df, y='GDP (log scale)')
plt.title('Boxplot of GDP (Log Scale)')
plt.ylabel('GDP (Log Scale)')
plt.xlabel('Countries')

# f rate
plt.subplot(1, 2, 2)
sns.boxplot(data=df, y='Fertility rate, total (births per woman)')
plt.title('Boxplot of Fertility Rate')
plt.ylabel('Fertility Rate (births per woman)')
plt.xlabel('Countries')


plt.tight_layout()


plt.show()

# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns

# # Load the data from the uploaded file
# file_path =  '/content/drive/MyDrive/Country Development Indicators.csv'
# df = pd.read_csv(file_path)

# # Extract unique years
# years = df['Year'].unique()

# # Create boxplots for each year
# for year in years:
#     # Filter data for the specific year
#     df_year = df[df['Year'] == year]

#     # Creating a new figure for each year
#     plt.figure(figsize=(12, 6))

#     # Boxplot for GDP
#     plt.subplot(1, 2, 1)  # 1 row, 2 columns, 1st subplot
#     sns.boxplot(data=df_year, y='GDP')
#     plt.title(f'Boxplot of GDP for {year}')
#     plt.ylabel('GDP (in billions)')
#     plt.xlabel('Countries')

#     # Boxplot for Fertility Rate
#     plt.subplot(1, 2, 2)  # 1 row, 2 columns, 2nd subplot
#     sns.boxplot(data=df_year, y='Fertility rate, total (births per woman)')
#     plt.title(f'Boxplot of Fertility Rate for {year}')
#     plt.ylabel('Fertility Rate (births per woman)')
#     plt.xlabel('Countries')

#     # Displaying the combined plot
#     plt.tight_layout()
#     plt.show()

# Apply log transformation to GDP
df['GDP_log'] = np.log1p(df['GDP'])


for year in years:

    df_year = df[df['Year'] == year]

    plt.figure(figsize=(12, 6))

    # Boxplot for log
    plt.subplot(1, 2, 1)
    sns.boxplot(data=df_year, y='GDP_log')
    plt.title(f'Boxplot of GDP (Log Scale) for {year}')
    plt.ylabel('GDP')


    y_ticks = plt.yticks()
    original_values = np.round(np.expm1(y_ticks[0]), 2)
    new_labels = [f"{original:.2f} ({log_val:.2f})" for original, log_val in zip(original_values, y_ticks[0])]
    plt.yticks(y_ticks[0], new_labels)

    #F Rate
    plt.subplot(1, 2, 2)
    sns.boxplot(data=df_year, y='Fertility rate, total (births per woman)')
    plt.title(f'Boxplot of Fertility Rate for {year}')
    plt.ylabel('Fertility Rate (births per woman)')
    plt.xlabel('Countries')


    plt.tight_layout()

    plt.show()

import matplotlib.pyplot as plt
import seaborn as sns


plt.figure(figsize=(12, 6))
sns.boxplot(x='Country Classification', y='Fertility rate, total (births per woman)', data=df)
plt.title('Fertility Rate by Country Development Classification')
plt.ylabel('Fertility Rate (births per woman)')
plt.xlabel('Country Development Classification')
plt.xticks(rotation=45)
plt.show()